language: node_js
node_js:
  - "lts/*"
after_success:
  - npm install codecov -g
  - codecov
jobs:
  include:
    - stage: test
    - stage: push docker images
      if: branch IN (master, ocrvs-332-auto-deploy)
      script: yarn compose:push
      sudo: required
      services:
        - docker
    - stage: deploy to staging
      if: branch IN (master, ocrvs-332-auto-deploy)
      install: skip
      script: yarn deploy:staging
