language: node_js
node_js:
  - "lts/*"
jobs:
  include:
    - stage: test
      after_success:
        - npm install codecov -g
        - codecov
    - stage: push docker images
      if: branch = master AND type = push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - yarn compose:push
      sudo: required
      services:
        - docker
    - stage: deploy to staging
      if: branch = master AND type = push
      install: skip
      script: yarn deploy:staging
      addons:
        ssh_known_hosts: opencrvs-staging.jembi.org
