language: node_js
node_js:
  - "lts/*"
cache: yarn
jobs:
  include:
    - stage: unit tests
      after_success:
        - npm install codecov -g
        - codecov

    - stage: integration tests
      script:
        - yarn dev:secrets:gen
        - yarn compose -d
        - sleep 10
        - yarn start &
        - sleep 60
        - cd packages/user-mgnt && yarn populate && cd ../..
        - cd packages/e2e && yarn start --record
      env:
        CYPRESS_REGISTER_URL=http://localhost:3020/
      services:
        - docker

    - stage: build and push docker images
      # if: branch = master AND type = push
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - yarn compose:push
      sudo: required
      services:
        - docker

    - stage: deploy to staging
      if: branch = master AND type = push
      install: skip
      script: yarn deploy:staging
      addons:
        ssh_known_hosts: opencrvs-staging.jembi.org

    - stage: integration tests on staging
      if: branch = master AND type = push
      install: skip
      script: cd packages/e2e && yarn && yarn start --record
      env:
        CYPRESS_REGISTER_URL=http://opencrvs-staging.jembi.org:5040/
