language: node_js
node_js:
  - "lts/*"
cache: yarn
jobs:
  include:
    - stage: travis_retry test
      after_success:
        - npm install codecov -g
        - codecov
    - stage: push docker images
      if: branch = master AND type = push
      install: skip
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - yarn compose:push
      sudo: required
      services:
        - docker
    - stage: deploy to staging
      if: branch = master AND type = push
      install: skip
      script: yarn deploy:staging
      addons:
        ssh_known_hosts: opencrvs-staging.jembi.org

    - stage: run integration tests
      # if: branch = master AND type = push
      install: skip
      script: cd packages/e2e && yarn start
      env:
        CYPRESS_REGISTER_URL=http://opencrvs-staging.jembi.org:5040/