version: '3.3'

services:
  # Setup our apps to run in dev mode with under the default user
  register:
    command: yarn start
    user: '1000'
    volumes:
      - './node_modules:/usr/src/app/node_modules'
      - './packages:/usr/src/app/packages'

  performance:
    command: yarn start
    user: '1000'
    volumes:
      - './node_modules:/usr/src/app/node_modules'
      - './packages:/usr/src/app/packages'

  login:
    command: yarn start
    user: '1000'
    volumes:
      - './node_modules:/usr/src/app/node_modules'
      - './packages:/usr/src/app/packages'

  gateway:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/gateway:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

  workflow:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/workflow:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

  deduplication:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/deduplication:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

  auth:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/auth:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

  user-mgnt:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/user-mgnt:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

  notification:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/notification:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

  resources:
    command: yarn start
    user: '1000'
    volumes:
      - './packages/resources:/usr/src/app'
      - './node_modules:/usr/src/app/node_modules'

# For dependencies, expose ports locally for dev
  mongo:
    ports:
      - '27017:27017'
    volumes:
      - './data/mongo:/data/db'
  redis:
    ports:
      - '6379:6379'

  elasticsearch:
    ports:
      - '9200:9200'
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'

  influxdb:
    ports:
      - '8086:8086'
    volumes:
      - './data/influxdb:/var/lib/influxdb'

  # Expose dev secrets as a plain volume - these will use docker secrets in staging and prod
  hearth:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
      - './infrastructure/hearth-plugins/checkDuplicateTask.js:/src/hearth/lib/plugins/checkDuplicateTask.js'
      - './infrastructure/hearth-queryparam-extensions.json:/src/hearth/config/queryparam-extensions.json'
    ports:
      - '3447:3447'

  # Expose config as a plain volume - these will use docker config in staging and prod
  openhim-console:
    volumes:
      - './infrastructure/openhim-console-config.json:/usr/share/nginx/html/config/default.json'
