version: "3"

services:
  client:
    container_name: ocrvs-client
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    restart: unless-stopped
    ports:
      - "5050:5000"

  gateway:
    container_name: ocrvs-gateway
    build: packages/gateway
    restart: unless-stopped
    ports:
      - "7070:7070"
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
