version: "3.3"

# Expose ports locally for dev
services:
  mongo:
    ports:
      - "27017:27017"
  redis:
    ports:
      - "6379:6379"
  hearth:
    ports:
      - "3447:3447"

  # Expose dev secrets as a plain volume - these will use docker secrets in staging and prod
  hearth:
    volumes:
      - ".secrets/public-key.pem:/secrets/public-key.pem"

  # Expose config as a plain volume - these will use docker config in staging and prod
  openhim-console:
    volumes:
      - "./infrastructure/openhim-console-config.json:/usr/share/nginx/html/config/default.json"
