version: "3.3"

services:
  client:
    image: jembi/ocrvs-client:latest
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    restart: unless-stopped
    ports:
      - "5050:5000"
    deploy:
      replicas: 2

  gateway:
    image: jembi/ocrvs-gateway:latest
    build: packages/gateway
    restart: unless-stopped
    ports:
      - "7070:7070"
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
    deploy:
      replicas: 2
