version: "3.3"

services:
  register:
    image: jembi/ocrvs-register:latest
    build:
      context: .
      dockerfile: ./Dockerfile-register
    restart: unless-stopped
    ports:
      - "5050:5000"
    environment:
      - NODE_ENV=DEVELOPMENT
      - REACT_APP_API_GATEWAY_URL=http://localhost:7070/
      - REACT_APP_LOCALE=gb
      - REACT_APP_LANGUAGE=en
    deploy:
      replicas: 2

  login:
    image: jembi/ocrvs-login:latest
    build:
      context: .
      dockerfile: ./Dockerfile-login
    restart: unless-stopped
    ports:
      - "5040:5000"
    environment:
      - NODE_ENV=DEVELOPMENT
      - REACT_APP_AUTH_API_URL=http://localhost:4040/
      - REACT_APP_LOCALE=gb
      - REACT_APP_LANGUAGE=en
    deploy:
      replicas: 2

  gateway:
    image: jembi/ocrvs-gateway:latest
    build: packages/gateway
    restart: unless-stopped
    ports:
      - "7070:7070"
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
    deploy:
      replicas: 2
