version: "3.3"

services:
  register:
    image: jembi/ocrvs-register:latest
    build:
      context: .
      dockerfile: ./Dockerfile-register
    restart: unless-stopped
    ports:
      - "5050:5000"
    environment:
      - NODE_ENV=DEVELOPMENT
      - REACT_APP_API_GATEWAY_URL=http://opencrvs-staging.jembi.org:7070/
      - REACT_APP_LOCALE=gb
      - REACT_APP_LANGUAGE=en
    deploy:
      replicas: 2

  login:
    image: jembi/ocrvs-login:latest
    build:
      context: .
      dockerfile: ./Dockerfile-login
    restart: unless-stopped
    ports:
      - "5040:5000"
    environment:
      - NODE_ENV=DEVELOPMENT
      - REACT_APP_AUTH_API_URL=http://opencrvs-staging.jembi.org:4040/
      - REACT_APP_LOCALE=gb
      - REACT_APP_LANGUAGE=en
    deploy:
      replicas: 2

  gateway:
    image: jembi/ocrvs-gateway:latest
    build: packages/gateway
    restart: unless-stopped
    ports:
      - "7070:7070"
    environment:
      - NODE_ENV=DEVELOPMENT
      - FHIR_URL=http://openhim-core:5001/fhir
    deploy:
      replicas: 2

  auth:
    image: jembi/ocrvs-auth:latest
    build: packages/auth
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - CONFIG_TOKEN_EXPIRY=600
      - NOTIFICATION_SERVICE_URL=http://localhost:2020/
    ports:
      - "4040:4040"
    deploy:
      replicas: 2

  user-mgnt:
    image: jembi/ocrvs-user-mgnt:latest
    build: packages/user-mgnt
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - MONGO_URL=mongodb://mongo/user-mgnt
    deploy:
      replicas: 2

  notification:
    image: jembi/ocrvs-notification:latest
    build: packages/notification
    restart: unless-stopped
    ports:
      - "2020:2020"
    deploy:
      replicas: 2
