version: '3.3'

services:
  notification:
    secrets:
      - infobip-gateway-endpoint
      - infobip-api-key
      - infobip-sender-id
    environment:
      - LANGUAGES=bn,en
      - SMS_PROVIDER=infobip
      - INFOBIP_GATEWAY_ENDPOINT_PATH=/run/secrets/infobip-gateway-endpoint
      - INFOBIP_API_KEY_PATH=/run/secrets/infobip-api-key
      - INFOBIP_SENDER_ID=/run/secrets/infobip-sender-id

  workflow:
    environment:
      - LANGUAGES=bn,en

secrets:
  infobip-gateway-endpoint:
    external: true
  infobip-api-key:
    external: true
  infobip-sender-id:
    external: true
