# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
name: Clear and restore config backup data

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to clear and restore config backup
        required: true
        options:
          - qa
          - config
      replicas:
        description: No of replicas deployed in the environemt
        default: "1"
        required: true
jobs:
  clear:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      REPLICAS: ${{ github.event.inputs.replicas }}
      SRC_HOST: farajaland-${{ github.event.inputs.environment }}.opencrvs.org
      MONGODB_ADMIN_USER: ${{ secrets.MONGODB_ADMIN_USER }}
      MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
      ELASTICSEARCH_ADMIN_USER: elastic
      ELASTICSEARCH_ADMIN_PASSWORD: ${{ secrets.ELASTICSEARCH_SUPERUSER_PASSWORD }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Clear config backup data in given environment
        run: ssh root@$SRC_HOST "MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER MONGODB_ADMIN_PASSWORD=$MONGODB_ADMIN_PASSWORD ELASTICSEARCH_ADMIN_USER=$ELASTICSEARCH_ADMIN_USER ELASTICSEARCH_ADMIN_PASSWORD=$ELASTICSEARCH_ADMIN_PASSWORD /opt/opencrvs/infrastructure/clear-all-data.sh $REPLICAS $ENV"
      - name: Restore config backup data in given environment
        run: ssh root@$SRC_HOST "MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER MONGODB_ADMIN_PASSWORD=$MONGODB_ADMIN_PASSWORD /opt/opencrvs/infrastructure/restore-metadata.sh $REPLICAS $ENV"
