# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
name: Create backup data

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to create backup from
        required: true
        options:
          - staging
          - qa
          - production
          - config
      backup_environment:
        type: choice
        description: Environment to create backups to
        required: true
        default: config
        options:
          - staging
          - qa
          - production
          - config
      replicas:
        description: No of replicas deployed in the environemt
        required: true
      version_label:
        description: The version label for the backups
        required: true
jobs:
  backup:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      BACKUP_HOST: farajaland-${{ github.event.inputs.backup_environment }}.opencrvs.org
      SSH_HOST: farajaland-${{ github.event.inputs.environment }}.opencrvs.org
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Run emergency-backup-metadata in given environment
        run: |
          ssh root@$SSH_HOST
          cd /opt/opencrvs/infrastructure
          ./emergency-backup-metadata.sh root $BACKUP_HOST 22 $SSH_HOST /data/backups/ ${{ github.event.inputs.replicas }} ${{ github.event.inputs.version_label }}

