# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
name: Create backup data

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to create backup from
        required: true
        options:
          - staging
          - qa
          - production
          - config
      backup_environment:
        type: choice
        description: Environment to create backups to
        required: true
        default: config
        options:
          - staging
          - qa
          - production
          - config
      replicas:
        description: No of replicas deployed in the environemt
        required: true
      version_label:
        description: The version label for the backups
        required: true
jobs:
  backup:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      BACKUP_HOST: farajaland-${{ github.event.inputs.backup_environment }}.opencrvs.org
      SRC_HOST: farajaland-${{ github.event.inputs.environment }}.opencrvs.org
      VERSION_LABEL: ${{ github.event.inputs.version_label }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create backup data in given environment
        run: ssh root@$SRC_HOST "MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER MONGODB_ADMIN_PASSWORD=$MONGODB_ADMIN_PASSWORD ELASTICSEARCH_ADMIN_USER=$ELASTICSEARCH_ADMIN_USER ELASTICSEARCH_ADMIN_PASSWORD=$ELASTICSEARCH_ADMIN_PASSWORD /opt/opencrvs/infrastructure/emergency-backup-metadata.sh _1 _2 _3 _4 _5 ${{ github.event.inputs.replicas }} $VERSION_LABEL"
        env:
          MONGODB_ADMIN_USER: ${{ secrets.MONGODB_ADMIN_USER }}
          MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
          ELASTICSEARCH_ADMIN_USER: elastic
          ELASTICSEARCH_ADMIN_PASSWORD: ${{ secrets.ELASTICSEARCH_SUPERUSER_PASSWORD }}
      - name: Transfer the data to the backup environment
        run: |
          script -q -c "scp -v -r root@$SRC_HOST:/data/backups/elasticsearch/ root@$BACKUP_HOST:$REMOTE_DIR/elasticsearch/" && echo "Copied elasticsearch backup files to remote server."
          script -q -c "scp -v -r root@$SRC_HOST:/data/backups/influxdb/$VERSION_LABEL root@$BACKUP_HOST:$REMOTE_DIR/influxdb" && echo "Copied influx backup files to remote server."
          script -q -c "scp -v -r root@$SRC_HOST:/data/backups/mongo/hearth-dev-$VERSION_LABEL.gz root@$BACKUP_HOST:$REMOTE_DIR/mongo" && echo "Copied hearth backup files to remote server."
          script -q -c "scp -v -r root@$SRC_HOST:/data/backups/mongo/user-mgnt-$VERSION_LABEL.gz root@$BACKUP_HOST:$REMOTE_DIR/mongo" && echo "Copied user backup files to remote server."
          script -q -c "scp -v -r root@$SRC_HOST:/data/backups/mongo/openhim-dev-$VERSION_LABEL.gz root@$BACKUP_HOST:$REMOTE_DIR/mongo" && echo "Copied openhim backup files to remote server."
          script -q -c "scp -v -r root@$SRC_HOST:/data/backups/mongo/application-config-$VERSION_LABEL.gz root@$BACKUP_HOST:$REMOTE_DIR/mongo" && echo "Copied application-config backup files to remote server."
        env:
          REMOTE_DIR: /data/backups/

